# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.10-slim

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Create working dir
WORKDIR /app
COPY . /app

# Install pip requirements
RUN python -m pip install -r requirements.txt

# Add Python Path 
ENV PYTHONPATH "${PYTHONPATH}:/app/myPythonModule/"

# Add openssh-client to authenticate to git using SSH
RUN apt-get update && apt-get install -y openssh-client

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
# RUN echo 'root:Docker!' | chpasswd
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser